server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/*.xml

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/localpoidemo?useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
